// ⚠️ Warning: This file was automatically generated by `brail`.
// Any changes you make to this file will be overwritten.

// If you wish to make changes, you can manually import templates into another file and use that "template map".
// You can turn this auto-generation off via the `emitTemplates` option in your next/brail config.

import soPromotional2 from "../pages/stack-overflow/so-promotional-2.template";
import soPromotional from "../pages/stack-overflow/so-promotional.template";

export const templates = {
    stackOverflow: {
      soPromotional2,
      soPromotional
    }
}
