import path from "node:path";
import fs from "node:fs"
import { camelCase } from "../../../util/string.util";
import { BrailConfig } from "../types";
import { extractFileParts, isIgnored, isValidExtension } from "../util";


const GENERATED_FILE_WARNING =
  `// ⚠️ Warning: This file was automatically generated by \`brail\`.\n` +
  `// Any changes you make to this file will be overwritten.\n\n` +
  `// If you wish to make changes, you can manually import templates into another file and use that "template map".\n` +
  `// You can turn this auto-generation off via the \`emitTemplates\` option in your next/brail config.\n\n`;
